name: GoRelease

on:
  push:
    tags:
      - 'v*.*.*'
env:
  # Common versions
  GO_VERSION: '1.22'
  GO_REQUIRED_MIN_VERSION: ''
  GITHUB_REF: ${{ github.ref }}
  CHART_NAME: cluster-permission

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: images
        run:  make docker-build
      - name: get release version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: get major release version
        run: |
          echo "MAJOR_RELEASE_VERSION=${RELEASE_VERSION%.*}" >> $GITHUB_ENV
      - name: setup helm
        uses: azure/setup-helm@v4
      - name: chart package
        run: |
          mkdir -p release
          pushd release
          helm package ../chart/
          popd
      - name: push image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker tag quay.io/open-cluster-management/cluster-permission:latest quay.io/open-cluster-management/cluster-permission:$RELEASE_VERSION
          docker push quay.io/open-cluster-management/cluster-permission:$RELEASE_VERSION
      - name: generate changelog
        run: |
          echo "# cluster-permission $RELEASE_VERSION" > /home/runner/work/changelog.txt
          echo "- See the [CHANGELOG](https://github.com/open-cluster-management-io/cluster-permission/blob/main/CHANGELOG/CHANGELOG-${MAJOR_RELEASE_VERSION}.md) for more details." >> /home/runner/work/changelog.txt
          echo "- The released image is quay.io/open-cluster-management/cluster-permission:$RELEASE_VERSION" >> /home/runner/work/changelog.txt
      - name: publish release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: /home/runner/work/changelog.txt
          files: |
            release/*.tgz
          draft: true
          prerelease: false
          generate_release_notes: true
